# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

steps:
#- task: PowerShell@2
#  inputs:
#    filePath: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts\Download_simple.ps1'
#    arguments: HDDRXM0.DEMO.COB.BATCH

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $downloader = [SCM_Downloader]::new('$(hostPdsName)')
      $downloader.download()
      
      Class SCM_Downloader{
      
          [string]$cliPath
          [string]$downloadType
          [string]$hostUri
          [string]$hostPort
          [string]$hostCodepage
          [string]$hostUser
          [string]$hostPassword
          [string]$extension
          [string]$hostPdsName
      
          SCM_Downloader([string] $hostPdsName)
          {
              $this.cliPath = "C:\Users\cwde-rnuesse.EMEA\Software\Compuware\TopazCLI\"
              $this.downloadType = "pds"
              $this.hostUri = "cwcc.compuware.com"
              $this.hostPort = "16196"
              $this.hostCodePage = "1047"
              $this.hostUser = "hddrxm0"
              $this.hostPassword = "cpwr2001"
              $this.extension = "cbl"
              $this.hostPdsName = $hostPdsName
          }
      
          download()
          {
              $command = $this.cliPath + "SCMDownloaderCLI.bat" + 
                  " -host " + $this.hostUri +
                  " -port " + $this.hostPort +
                  " -id " + $this.hostUser +
                  " -pass " + $this.hostPassword +
                  " -code " + $this.hostCodePage +
                  " -timeout 0" + 
                  " -scm " + $this.downloadType +
                  " -targetFolder " + ".\MF_Sources" +
                  " -data " + ".\workspace\Test\TopazCliWkspc1e290c49-0de6-44c4-b8d2-01d0cb40a835" +
                  " -filter " + $this.hostPdsName +
                  " -ext " + $this.extension
      
              iex $command
          }
      }