# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts\Download.ps1'
    arguments: $(hostSourcesPds)

- task: PowerShell@2
  inputs:
    filePath: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts\Download.ps1'
    arguments: $(hostCopyPds)

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      [string]$hostPdsName = '$(hostPdsName)'
#      [string]$workFolder = 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts'
#      [string]$cliPath = "C:\Users\cwde-rnuesse.EMEA\Software\Compuware\TopazCLI\"
#      [string]$downloadType = "pds"
#      [string]$hostUri = "cwcc.compuware.com"
#      [string]$hostPort = "16196"
#      [string]$hostCodePage = "1047"
#      [string]$hostUser = "hddrxm0"
#      [string]$hostPassword = "cpwr2001"
#      [string]$extension = "cbl"
#      
#      CD C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts
#      C:\Users\cwde-rnuesse.EMEA\Software\Compuware\TopazCLI\SCMDownloaderCLI.bat -host $hostUri -port $hostPort -id $hostUser -pass $hostPassword -code $hostCodePage -timeout 0 -scm $downloadType -targetFolder .\MF_Sources -data .\workspace\Test\TopazCliWkspc -filter $hostPdsName -ext $extension