trigger:
- master

pool:
  name: 'Default'

variables:
  sonarProjectName: 'RNU_Azure_ISPW'
  workspaceRoot: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Workspace'
  sonarSources: '.\$(ispwApplication)\MF_Source'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts\Download_ispw_cont.ps1'
    arguments: '$(ispwContainerName) $(ispwContainerType) $(ispwLevel)'

- task: BatchScript@1
  inputs:
    filename: 'C:\Users\cwde-rnuesse.EMEA\Software\Sonar\Scanner\bin\sonar-scanner'
    arguments: '-Dsonar.projectBaseDir=$(workspaceRoot) -Dsonar.projectKey=$(sonarProjectName) -Dsonar.projectName=$(sonarProjectName) -Dsonar.projectVersion=1.0 -Dsonar.sources=$(sonarSources) -Dsonar.cobol.copy.directories=$(sonarSources) -Dsonar.cobol.copy.suffixes=cpy -Dsonar.cobol.file.suffixes=cbl'

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'GitHub connection 1'
    userRepository: 'ralphnuessecpwr/FTSDEMO_$(ispwApplication)_Unit_Tests'
    defaultVersionType: 'latest'
    downloadPath: '$(workspaceRoot)\tests'