trigger:
- master

pool:
  name: 'Default'

variables:
  agentScriptsPath: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Scripts'
  workspaceRoot: 'C:\Users\cwde-rnuesse.EMEA\Software\Azure_DevOps_Workspace'
  hostUri: 'cwcc.compuware.com'
  hostPort: '16196'
  hostCodePage: '1047'
  ispwConfig: 'ispw'
  gitProject: 'ralphnussecpwr'
  gitRepo: 'FTSDEMO_$(ispwApplication)_Unit_Tests'
  ccRepo: 'HDDRXM0.DEMO.COCO.REPO'
  sonarScannerPath: 'C:\Users\cwde-rnuesse.EMEA\Software\Sonar\Scanner\bin'
  sonarProjectName: 'RNU_Azure_ISPW'
  sonarSources: '.\$(ispwApplication)\MF_Source'

steps:
- task: PowerShell@2
  inputs:
    filePath: '$(agentScriptsPath)\Download_ispw_cont.ps1'
    arguments: '$(workspaceRoot) $(hostUri) $(hostPort) $(hostCodePage) $(ispwConfig) $(ispwContainerName) $(ispwContainerType) $(ispwLevel)'

- task: PowerShell@2
  inputs:
    filePath: '$(agentScriptsPath)\Git.ps1'
    arguments: '$(workspaceRoot) $(gitProject)/$(gitRepo)'

- task: PowerShell@2
  inputs:
    filePath: '$(agentScriptsPath)\TTT.ps1'
    arguments: '$(workspaceRoot) $(hostUri) $(hostPort) $(hostCodePage) $(ispwLevel) $(ccRepo)'

#- task: BatchScript@1
#  inputs:
#    filename: '$(sonarScannerPath)\sonar-scanner'
#    arguments: '-Dsonar.projectBaseDir=$(workspaceRoot) -Dsonar.projectKey=$(sonarProjectName) -Dsonar.projectName=$(sonarProjectName) -Dsonar.projectVersion=1.0 -Dsonar.sources=$(sonarSources) -Dsonar.cobol.copy.directories=$(sonarSources) -Dsonar.cobol.copy.suffixes=cpy -Dsonar.cobol.file.suffixes=cbl'
